### ISSUE TITLE
Service not installed

### ISSUE THREAD

**Issue by eNTe96** [ZiMADE/EmoKill#3]
Output on Win1909x64 when using your Console to install:

Result:
Microsoft (R) .NET Framework-Installationsprogramm, Version 4.8.3752.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
Beim Initialisieren der Installation ist eine Ausnahme aufgetreten:
System.IO.FileLoadException: Die Datei oder Assembly "file:///C:\Program Files\EmoKill\EmoKill.exe" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)
Service State: UNKNOWN

**Comment by ZiMADE** [comment]
Please have a lock to program files folder (C:\Program Files\EmoKill or in German C:\Programme\EmoKill). Installing EmoKill as a Service first of all the files will be copied to the program files folder. After that the service will be installed with the installutil.exe of .net-framework.

If all files are exists at the program files folder, you may try to install the service with the following command (you must run it from a command shell as administrator):  
`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\installutil.exe` "C:\Program `Files\EmoKill\EmoKill.exe"`

**Comment by eNTe96** [comment]
That gave the same exception 0x80131515
I just had to 'Unblock' EmoKill.exe at file properties General tab
Thanks for the nice tool!

**Comment by ZiMADE** [comment]
Thank you for your feedback
